[package]
name = "litedb"
version = "0.1.0"
edition = "2024"

[dependencies]
async-lock = "3.4.0"
futures = "0.3.31"

[dev-dependencies]
time = { version = "0.3.37", features = ["macros"] }

[features]
debug-logs = []
